 sources:
  - name : raw
    schema : dbt
    tables :
      - name : products
        identifier: raw_gz_product
          - name: products_id
          - name: purchSE_PRICE


  - name: raw_gz_ship
    columns:
      - name: orders_id
      - name: shipping_fee
      - name: shipping_fee_1
      - name: logCost
      - name: ship_cost

  - name: raw_gz_sales
    columns:
      - name: date_date
      - name: orders_id
      - name: pdt_id
      - name: revenue
      - name: quantity