 sources:
  - name : raw
    schema : dbt
    tables :
      - name : products
        identifier: raw_gz_product
        columns :
          - name: products_id
          - name: purchSE_PRICE

  - name: sales
    identifier: raw_gz_sales
    columns:
      - name: date_date
      - name: orders_id
      - name: pdt_id
      - name: revenue
      - name: quantity