version: 2

sources:
  - name : raw
    schema : dbt
    tables :
      - name : products
        identifier: raw_gz_product
        description: product table
      - name : sales
        identifier : raw_gz_sales
        description : sales table

      - name : ship
        identifier : raw_gz_ship
        description : ship table